#!/bin/bash

BUILD_VERSION=$2
FILE_PATH=GRCh${BUILD_VERSION}
FILENAME=$1
SAMPLE_TYPE=$3
INDEX_NAME=$4
INPUT_FILE_PATH=${FILE_PATH}/${FILENAME}

docker-compose exec pipeline-runner load_data.sh $BUILD_VERSION $SAMPLE_TYPE $INDEX_NAME $INPUT_FILE_PATH